Repository LaGGgggg/yp_p2p_api, pull requests merged in 2024-02, with the labels that each got.

#1 feat: базовая архитектура
  API/__init__.py
  API/alembic.ini
  API/core/__init__.py
  API/core/config.py
  API/core/get_logger.py
  API/core/login_manager.py
  API/core/main.py
  API/core/schemas.py
  API/migrations/README
  API/migrations/env.py
  API/migrations/script.py.mako
  API/migrations/versions/a21bb900e85b_.py
  API/routers/__init__.py
  API/routers/system.py
  API/routers/users.py
  API/sql/__init__.py
  API/sql/crud.py
  API/sql/database.py
  API/sql/models.py
  API/utils.py
  README.md
  docker-compose-init.sh
  docker-compose.yml
  dockerfiles/Dockerfile-web
  nginx/Dockerfile
  nginx/nginx.conf
  requirements.txt
  web-entrypoint.sh
Labels: enhancement

#2 feat: правила для колобараторов
  README.md
Labels: documentation, enhancement

#6 Feat: система регистрации
  API/core/config.py
  API/core/schemas.py
  API/migrations/versions/0c2ed5e1a2f1_.py
  API/routers/users.py
  API/sql/crud.py
  API/sql/models.py
  API/utils.py
  README.md
Labels: enhancement

#3 feat: crud на классах
  .gitignore
  API/core/main.py
  API/core/schemas.py
  API/routers/users.py
  API/sql/crud.py
  API/utils.py
Labels: enhancement

#7 fix: исправлен метод get_many в BaseCrud
  API/sql/crud.py
Labels: bug

#8 feat: ненулевые значения
  API/migrations/versions/a930d03d907d_.py
  API/sql/models.py
Labels: enhancement

#10 feat: улучшена читаемость логов за счёт цвета
  API/utils.py
Labels: enhancement

#9 Добавлена поддержка тестирования с pytest и автоматического тестирования с GitHub actions
  .github/workflows/project_tests.yml
  API/core/config.py
  API/core/main.py
  API/core/schemas.py
  API/migrations/env.py
  API/pytest.ini
  API/pytest_runner.py
  API/routers/users.py
  API/sql/crud.py
  API/sql/database.py
  API/tests/_testing_utils.py
  API/tests/test_system.py
  API/tests/test_users.py
  README.md
  requirements.txt
Labels: enhancement

#11 feat: возможность создания p2p request-а
  API/core/config.py
  API/core/main.py
  API/core/schemas.py
  API/migrations/env.py
  API/migrations/versions/5ea3d3527a03_.py
  API/routers/p2p_request.py
  API/routers/users.py
  API/sql/crud.py
  API/sql/models.py
  requirements.txt
Labels: enhancement
