Repository LaGGgggg/yp_p2p_api, pull requests merged in 2024-03, with the labels that each got.

#12 feat: возможность создания review request-а
  API/core/schemas.py
  API/migrations/versions/cdd89efd0474_.py
  API/routers/p2p_request.py
  API/sql/crud.py
  API/sql/models.py
  API/sql/models_choices_enums.py
Labels: enhancement

#14 fix: убран ненужный RUN
  dockerfiles/Dockerfile-web
Labels: bug

#13 fix: уязвимость в работе с сессиями базы данных
  API/core/main.py
  API/pytest_runner.py
  API/routers/users.py
  API/sql/database.py
  API/tests/_testing_utils.py
  API/tests/test_users.py
  API/utils.py
Labels: bug

#17 feat: добавлена возможность создания review на p2p request
  API/core/schemas.py
  API/migrations/versions/2a21ae496bbc_.py
  API/routers/p2p_request.py
  API/sql/crud.py
  API/sql/models.py
Labels: enhancement

#18 Перемещаем MVC в main ветку
  .github/workflows/project_tests.yml
  .gitignore
  API/__init__.py
  API/alembic.ini
  API/core/__init__.py
  API/core/config.py
  API/core/get_logger.py
  API/core/login_manager.py
  API/core/main.py
  API/core/schemas.py
  API/migrations/README
  API/migrations/env.py
  API/migrations/script.py.mako
  API/migrations/versions/2a21ae496bbc_.py
  API/migrations/versions/5acd0e76053c_.py
  API/pytest.ini
  API/pytest_runner.py
  API/routers/__init__.py
  API/routers/p2p_request.py
  API/routers/system.py
  API/routers/users.py
  API/sql/__init__.py
  API/sql/crud.py
  API/sql/database.py
  API/sql/models.py
  API/sql/models_enums.py
  API/tests/_testing_utils.py
  API/tests/test_system.py
  API/tests/test_users.py
  API/utils.py
  README.md
  docker-compose-init.sh
  docker-compose.yml
  dockerfiles/Dockerfile-web
  nginx/Dockerfile
  nginx/nginx.conf
  requirements.txt
  web-entrypoint.sh
Labels: enhancement

#20 Исправления продакшен конфигов и их документации
  README.md
  nginx/nginx.conf
  web-entrypoint.sh
Labels: bug, documentation

#21 Исправления продакшен конфигов и их документации
  README.md
  nginx/nginx.conf
  web-entrypoint.sh
Labels: bug, documentation

#23 feat: добавлен route для получения списка review
  API/core/schemas.py
  API/routers/p2p_request.py
Labels: enhancement

#25 feat: route, возвращающий список p2p request-ов
  API/routers/p2p_request.py
Labels: enhancement

#24 feat: теперь завершение review происходит по его id
  API/routers/p2p_request.py
Labels: enhancement
